import type React from "react";
import type { ApiAuth } from "../api";
import type { AgentUIDefaults, ConnectionMode, HostPolicy, ToolMode } from "../runtime_config";
import type { ConnectionProfile } from "./uiSettingsProfiles";

export type ServerPrefsAutoStatus = "idle" | "checking" | "ready" | "unsupported" | "auth_required" | "error";

export type ConnectionSettings = {
  profiles: ConnectionProfile[];
  activeProfileId: string;
  setActiveProfileId: (next: string) => void;
  profileName: string;
  setProfileName: React.Dispatch<React.SetStateAction<string>>;
  addProfile: (mode?: ConnectionMode) => void;
  duplicateProfile: () => void;
  deleteProfile: (id: string) => void;
  mode: ConnectionMode;
  setMode: React.Dispatch<React.SetStateAction<ConnectionMode>>;
  base: string;
  setBase: React.Dispatch<React.SetStateAction<string>>;
  brokerBase: string;
  setBrokerBase: React.Dispatch<React.SetStateAction<string>>;
  brokerAgentId: string;
  setBrokerAgentId: React.Dispatch<React.SetStateAction<string>>;
  brokerDeploymentId: string;
  setBrokerDeploymentId: React.Dispatch<React.SetStateAction<string>>;
  brokerCookieAuth: boolean;
  setBrokerCookieAuth: React.Dispatch<React.SetStateAction<boolean>>;
  brokerAuthToken: string;
  setBrokerAuthToken: React.Dispatch<React.SetStateAction<string>>;
  brokerCookieSessionStatus: "idle" | "exchanging" | "ready" | "error";
  brokerCookieSessionError: string | null;
  clearBrokerAuthCookie: () => Promise<void>;
  daemonAuthToken: string;
  setDaemonAuthToken: React.Dispatch<React.SetStateAction<string>>;
  serverPrefsEnabled: boolean;
  serverPrefsAuto: boolean;
  serverPrefsUserSet: boolean;
  serverPrefsAutoStatus: ServerPrefsAutoStatus;
  serverPrefsAutoError: string | null;
  clearServerPrefsOverride: () => void;
  setServerPrefsEnabled: React.Dispatch<React.SetStateAction<boolean>>;
  serverPrefsStatus: "idle" | "loading" | "error" | "synced";
  serverPrefsError: string | null;
  serverPrefsLastSyncMs: number | null;
  serverPrefsBase: string;
  pullServerPrefs: () => void;
  pushServerPrefs: () => void;
  effectiveBase: string;
  effectiveSseBase: string;
  daemonAuth: ApiAuth;
  authKey: string;
};

export type RunSettings = {
  profileOverridesEnabled: boolean;
  setProfileOverridesEnabled: React.Dispatch<React.SetStateAction<boolean>>;
  copyProfileOverridesFromGlobal: () => void;
  clearProfileOverrides: () => void;
  tools: ToolMode;
  setTools: React.Dispatch<React.SetStateAction<ToolMode>>;
  yolo: boolean;
  setYolo: React.Dispatch<React.SetStateAction<boolean>>;
  hostPolicy: HostPolicy;
  setHostPolicy: React.Dispatch<React.SetStateAction<HostPolicy>>;
  automationProfile: string;
  setAutomationProfile: React.Dispatch<React.SetStateAction<string>>;
  verbose: boolean;
  setVerbose: React.Dispatch<React.SetStateAction<boolean>>;
  model: string;
  setModel: React.Dispatch<React.SetStateAction<string>>;
  summaryModel: string;
  setSummaryModel: React.Dispatch<React.SetStateAction<string>>;
  summaryMaxChars: string;
  setSummaryMaxChars: React.Dispatch<React.SetStateAction<string>>;
  baseUrl: string;
  setBaseUrl: React.Dispatch<React.SetStateAction<string>>;
  apiKey: string;
  setApiKey: React.Dispatch<React.SetStateAction<string>>;
  proxyUrl: string;
  setProxyUrl: React.Dispatch<React.SetStateAction<string>>;
  timeoutMs: string;
  setTimeoutMs: React.Dispatch<React.SetStateAction<string>>;
  maxCaptureBytes: string;
  setMaxCaptureBytes: React.Dispatch<React.SetStateAction<string>>;
  streamAssistant: boolean;
  setStreamAssistant: React.Dispatch<React.SetStateAction<boolean>>;
  trace: boolean;
  setTrace: React.Dispatch<React.SetStateAction<boolean>>;
  useAsync: boolean;
  setUseAsync: React.Dispatch<React.SetStateAction<boolean>>;
  maxSteps: string;
  setMaxSteps: React.Dispatch<React.SetStateAction<string>>;
  maxRepeatedToolCalls: string;
  setMaxRepeatedToolCalls: React.Dispatch<React.SetStateAction<string>>;
  maxToolCallsTotal: string;
  setMaxToolCallsTotal: React.Dispatch<React.SetStateAction<string>>;
  maxToolCallsPerTool: string;
  setMaxToolCallsPerTool: React.Dispatch<React.SetStateAction<string>>;
  toolCallLimits: string;
  setToolCallLimits: React.Dispatch<React.SetStateAction<string>>;
  maxChars: string;
  setMaxChars: React.Dispatch<React.SetStateAction<string>>;
  keepLast: string;
  setKeepLast: React.Dispatch<React.SetStateAction<string>>;
  memoryContextMode: string;
  setMemoryContextMode: React.Dispatch<React.SetStateAction<string>>;
  memoryIncludeStructured: boolean;
  setMemoryIncludeStructured: React.Dispatch<React.SetStateAction<boolean>>;
  memoryIncludeCore: boolean;
  setMemoryIncludeCore: React.Dispatch<React.SetStateAction<boolean>>;
  memoryIncludeDaily: boolean;
  setMemoryIncludeDaily: React.Dispatch<React.SetStateAction<boolean>>;
  memoryIncludeSession: boolean;
  setMemoryIncludeSession: React.Dispatch<React.SetStateAction<boolean>>;
  memoryDailyDays: string;
  setMemoryDailyDays: React.Dispatch<React.SetStateAction<string>>;
  memoryTotalCap: string;
  setMemoryTotalCap: React.Dispatch<React.SetStateAction<string>>;
  memorySearchQuery: string;
  setMemorySearchQuery: React.Dispatch<React.SetStateAction<string>>;
  memorySearchOrder: string;
  setMemorySearchOrder: React.Dispatch<React.SetStateAction<string>>;
  memorySearchUseIndex: boolean;
  setMemorySearchUseIndex: React.Dispatch<React.SetStateAction<boolean>>;
  memorySearchCaseSensitive: boolean;
  setMemorySearchCaseSensitive: React.Dispatch<React.SetStateAction<boolean>>;
  memorySearchFallbackToFiles: boolean;
  setMemorySearchFallbackToFiles: React.Dispatch<React.SetStateAction<boolean>>;
  memorySearchMaxResults: string;
  setMemorySearchMaxResults: React.Dispatch<React.SetStateAction<string>>;
  memorySearchMaxSnippetChars: string;
  setMemorySearchMaxSnippetChars: React.Dispatch<React.SetStateAction<string>>;
  memorySearchContextLines: string;
  setMemorySearchContextLines: React.Dispatch<React.SetStateAction<string>>;
  orMinTotal: string;
  setOrMinTotal: React.Dispatch<React.SetStateAction<string>>;
  orMaxTotal: string;
  setOrMaxTotal: React.Dispatch<React.SetStateAction<string>>;
  orRequireMultimodal: boolean;
  setOrRequireMultimodal: React.Dispatch<React.SetStateAction<boolean>>;
  orRequireTools: boolean;
  setOrRequireTools: React.Dispatch<React.SetStateAction<boolean>>;
  orLimit: string;
  setOrLimit: React.Dispatch<React.SetStateAction<string>>;
};

export type ClientSettings = {
  clientId: string;
  setClientId: React.Dispatch<React.SetStateAction<string>>;
  allowAutoplay: boolean;
  setAllowAutoplay: React.Dispatch<React.SetStateAction<boolean>>;
  allowClientRpcs: boolean;
  setAllowClientRpcs: React.Dispatch<React.SetStateAction<boolean>>;
  allowClientEffects: boolean;
  setAllowClientEffects: React.Dispatch<React.SetStateAction<boolean>>;
  allowUnsafePageEval: boolean;
  setAllowUnsafePageEval: React.Dispatch<React.SetStateAction<boolean>>;
  showDebugInConversation: boolean;
  setShowDebugInConversation: React.Dispatch<React.SetStateAction<boolean>>;
};

export type UiSettings = {
  defaults: AgentUIDefaults;
  showSettings: boolean;
  setShowSettings: React.Dispatch<React.SetStateAction<boolean>>;
  connection: ConnectionSettings;
  run: RunSettings;
  client: ClientSettings;
  brokerPanelOpen: boolean;
  setBrokerPanelOpen: React.Dispatch<React.SetStateAction<boolean>>;
};
