export type BrokerTeamMemberRecord = Record<string, any>;

export type BrokerTeamMembersPanelProps = {
  canQuery: boolean;
  teamIdTrimmed: string;
  membersBusy: boolean;
  membersError: string | null;
  members: Array<BrokerTeamMemberRecord> | null;
  memberAgentsBusy: boolean;
  memberAgentsError: string | null;
  memberAgentOptions: Array<BrokerTeamMemberRecord>;
  memberAgentDeployments: Array<BrokerTeamMemberRecord>;
  memberEditAgentDeployments: Array<BrokerTeamMemberRecord>;
  memberId: string;
  memberRole: string;
  memberStatus: string;
  memberWeight: string;
  memberCapabilities: string;
  memberAgentId: string;
  memberDeploymentId: string;
  memberBackendLabel: string;
  memberModel: string;
  memberBaseUrl: string;
  memberSummaryModel: string;
  memberTools: string;
  memberTimeoutMs: string;
  memberEditId: string;
  memberEditRole: string;
  memberEditStatus: string;
  memberEditWeight: string;
  memberEditCapabilities: string;
  memberEditMetaJson: string;
  memberEditBackendLabel: string;
  memberEditModel: string;
  memberEditBaseUrl: string;
  memberEditSummaryModel: string;
  memberEditTools: string;
  memberEditTimeoutMs: string;
  memberEditAgentId: string;
  memberEditDeploymentId: string;
  memberEditBusy: boolean;
  memberEditError: string | null;
  onMemberIdChange: (next: string) => void;
  onMemberRoleChange: (next: string) => void;
  onMemberStatusChange: (next: string) => void;
  onMemberWeightChange: (next: string) => void;
  onMemberCapabilitiesChange: (next: string) => void;
  onMemberAgentIdChange: (next: string) => void;
  onMemberDeploymentIdChange: (next: string) => void;
  onMemberBackendLabelChange: (next: string) => void;
  onMemberModelChange: (next: string) => void;
  onMemberBaseUrlChange: (next: string) => void;
  onMemberSummaryModelChange: (next: string) => void;
  onMemberToolsChange: (next: string) => void;
  onMemberTimeoutMsChange: (next: string) => void;
  onMemberEditRoleChange: (next: string) => void;
  onMemberEditStatusChange: (next: string) => void;
  onMemberEditWeightChange: (next: string) => void;
  onMemberEditCapabilitiesChange: (next: string) => void;
  onMemberEditBackendLabelChange: (next: string) => void;
  onMemberEditModelChange: (next: string) => void;
  onMemberEditBaseUrlChange: (next: string) => void;
  onMemberEditSummaryModelChange: (next: string) => void;
  onMemberEditToolsChange: (next: string) => void;
  onMemberEditTimeoutMsChange: (next: string) => void;
  onMemberEditMetaJsonChange: (next: string) => void;
  onMemberEditAgentIdChange: (next: string) => void;
  onMemberEditDeploymentIdChange: (next: string) => void;
  onRefreshMembers: () => void;
  onAddMember: () => void;
  onRefreshMemberAgents: () => void;
  onAddConnectedAgents: () => void;
  onToggleMemberStatus: (member: BrokerTeamMemberRecord) => void;
  onEditMember: (member: BrokerTeamMemberRecord) => void;
  onDeleteMember: (memberId: string) => void;
  onSaveMemberEdit: () => void;
  onCancelMemberEdit: () => void;
  onSetAllMemberStatus: (status: "active" | "paused") => void;
  onRemovePausedMembers: () => void;
};
